service: default
runtime: go112
env: standard

handlers:
- url: /.*
  secure: optional
  script: auto

env_variables:
  # Replace INSTANCE_CONNECTION_NAME with the value obtained when configuring your
  # Cloud SQL instance, available from the Google Cloud Console or from the Cloud SDK.
  # For Cloud SQL 2nd generation instances, this should be in the form of "project:region:instance".
  GO_ENV: production
